//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type HasDockingPointSrvReq struct {
    msg.Package `ros:"mower_map"`
}



type HasDockingPointSrvRes struct {
    msg.Package `ros:"mower_map"`
    HasDockingPoint bool
}

type HasDockingPointSrv struct {
    msg.Package `ros:"mower_map"`
    HasDockingPointSrvReq
    HasDockingPointSrvRes
}
