//autogenerated:yes
//nolint:revive,lll
package mower_map

import (
    "github.com/bluenviron/goroslib/v2/pkg/msg"
)


type HasMowingAreaSrvReq struct {
    msg.Package `ros:"mower_map"`
}



type HasMowingAreaSrvRes struct {
    msg.Package `ros:"mower_map"`
    HasMowingArea bool
}

type HasMowingAreaSrv struct {
    msg.Package `ros:"mower_map"`
    HasMowingAreaSrvReq
    HasMowingAreaSrvRes
}
